version: "3.7"

services:
  nginx:
    build:
      context: nginx
    ports:
      - 80:80
    volumes:
      - ${PWD}/php/src:/var/www/html/magento2

  db:
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: userpwd
    ports:
      - 3306:3306

  php-fpm:
    user: ${UID}:${GID}
    build:
      context: php
    volumes:
      - ${PWD}/php/src:/var/www/html/magento2:delegated

  redis:
    image: redis:5.0.5-alpine3.10

#volumes:
#  nfsmount:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3,async
#      device: :${PWD}/php/src
